# Generated by Django 5.2.16 on 2026-08-02 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_keys', '0001_np200_api_keys'),
        ('organizations', '0003_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=16)),
                ('path', models.CharField(max_length=512)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_detail', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_logs', to='api_keys.apikey')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'API request log',
                'verbose_name_plural': 'API request logs',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['organization', 'created_at'], name='apilog_org_created_idx'), models.Index(fields=['organization', 'status_code', 'created_at'], name='apilog_org_status_idx')],
            },
        ),
    ]
