# Generated by Django 5.2.16 on 2026-08-02 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='working_days',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='OrganizationHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'organization holiday',
                'verbose_name_plural': 'organization holidays',
                'ordering': ('date',),
                'constraints': [models.UniqueConstraint(fields=('organization', 'date'), name='uniq_org_holiday_date')],
            },
        ),
    ]
