# Generated by Django 5.2.16 on 2026-08-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_np300_315_enterprise_kvkk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('FINANCE_MANAGER', 'Finance Manager'), ('COLLECTION_AGENT', 'Collection Agent'), ('VIEWER', 'Viewer'), ('EXTERNAL_LAWYER', 'External Lawyer')], default='VIEWER', max_length=32),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('FINANCE_MANAGER', 'Finance Manager'), ('COLLECTION_AGENT', 'Collection Agent'), ('VIEWER', 'Viewer'), ('EXTERNAL_LAWYER', 'External Lawyer')], max_length=32),
        ),
    ]
