# Generated by Django 5.2.16 on 2026-08-02 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_np193_customer_source_external'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
