# Generated by Django 5.2.17 on 2026-08-07 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_np211_214_workflow_engine'),
        ('organizations', '0004_np211_214_workflow_engine'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCommunicationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_ok', models.BooleanField(default=True)),
                ('whatsapp_ok', models.BooleanField(default=True)),
                ('sms_ok', models.BooleanField(default=True)),
                ('phone_ok', models.BooleanField(default=True)),
                ('no_contact_permission', models.BooleanField(default=False)),
                ('contact_hours_start', models.TimeField(blank=True, null=True)),
                ('contact_hours_end', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='communication_preference', to='customers.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'customer communication preference',
                'verbose_name_plural': 'customer communication preferences',
            },
        ),
    ]
