# Generated by Django 5.2.16 on 2026-08-07 22:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_np282_294_billing_onboarding'),
        ('organizations', '0005_np300_315_enterprise_kvkk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['organization', 'created_at'], name='cust_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['organization', 'assigned_user'], name='cust_org_assigned_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['organization', 'risk_status'], name='cust_org_risk_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['organization', 'source', 'external_id'], name='cust_org_src_ext_idx'),
        ),
    ]
