# Generated by Django 5.2.16 on 2026-08-07 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0004_np211_214_workflow_engine'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('help_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OnboardingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.CharField(choices=[('company', 'Şirket bilgileri'), ('invite', 'Kullanıcı daveti'), ('data_source', 'Veri kaynağı seçimi'), ('first_import', 'İlk veri aktarımı'), ('risk', 'Risk ayarları'), ('workflow', 'İlk tahsilat workflow’u'), ('dashboard', 'Dashboard sonucu')], default='company', max_length=32)),
                ('completed_steps', models.JSONField(blank=True, default=list)),
                ('wizard_completed', models.BooleanField(default=False)),
                ('sample_data_enabled', models.BooleanField(default=False)),
                ('flags', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization',), name='onboarding_one_state_per_org')],
            },
        ),
        migrations.CreateModel(
            name='ProductAnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(db_index=True, max_length=64)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'ordering': ('-occurred_at',),
                'indexes': [models.Index(fields=['organization', 'event_name', 'occurred_at'], name='onboarding__organiz_b1462c_idx')],
            },
        ),
    ]
