# Generated by Django 5.2.16 on 2026-08-07 22:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0005_np300_315_enterprise_kvkk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=16)),
                ('metric_name', models.CharField(max_length=64)),
                ('operator', models.CharField(default='>', max_length=8)),
                ('threshold', models.FloatField()),
                ('is_enabled', models.BooleanField(default=True)),
                ('runbook_key', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('key',),
            },
        ),
        migrations.CreateModel(
            name='StatusComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('web', 'Web uygulaması'), ('api', 'API'), ('integrations', 'Entegrasyonlar'), ('email', 'E-posta'), ('webhook', 'Webhook'), ('file_upload', 'Dosya yükleme'), ('reporting', 'Raporlama')], max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('state', models.CharField(choices=[('operational', 'Çalışıyor'), ('degraded', 'Yavaşlama'), ('partial_outage', 'Kısmi kesinti'), ('major_outage', 'Kesinti')], default='operational', max_length=32)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('value', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_events', to='organizations.organization')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ops.alertrule')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ArchiveRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=64)),
                ('older_than_days', models.PositiveIntegerField()),
                ('rows_moved', models.PositiveIntegerField(default=0)),
                ('dry_run', models.BooleanField(default=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoadTestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(default='small', max_length=32)),
                ('concurrent_users', models.PositiveIntegerField(default=1)),
                ('customers', models.PositiveIntegerField(default=0)),
                ('invoices', models.PositiveIntegerField(default=0)),
                ('activities', models.PositiveIntegerField(default=0)),
                ('timings_ms', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MetricSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('technical', 'Teknik'), ('business', 'İş')], max_length=16)),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('value', models.FloatField()),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metric_samples', to='organizations.organization')),
            ],
            options={
                'ordering': ('-recorded_at',),
                'indexes': [models.Index(fields=['name', 'recorded_at'], name='ops_metrics_name_ce0d4b_idx'), models.Index(fields=['organization', 'name', 'recorded_at'], name='ops_metrics_organiz_47d744_idx')],
            },
        ),
    ]
