# Generated by Django 5.2.16 on 2026-08-07 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_np194_invoice_source_external'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_sample',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('KOLAYBI', 'KolayBi'), ('SAMPLE', 'Örnek veri')], db_index=True, default='MANUAL', max_length=32),
        ),
    ]
