# Generated by Django 5.2.16 on 2026-08-07 22:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_np320_336_scale_ops'),
        ('invoices', '0004_np282_294_billing_onboarding'),
        ('organizations', '0005_np300_315_enterprise_kvkk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['organization', 'status', 'due_date'], name='inv_org_status_due_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['organization', 'customer', 'status'], name='inv_org_cust_status_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['organization', 'created_at'], name='inv_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['organization', 'source', 'external_id'], name='inv_org_src_ext_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['customer', 'due_date'], name='inv_customer_due_idx'),
        ),
    ]
