# Generated by Django 5.2.16 on 2026-08-07 22:18

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0007_np320_336_scale_ops'),
        ('organizations', '0005_np300_315_enterprise_kvkk'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgingBucketSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('bucket_code', models.CharField(max_length=32)),
                ('invoice_count', models.PositiveIntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'day', 'bucket_code'), name='uniq_aging_bucket_day')],
            },
        ),
        migrations.CreateModel(
            name='CollectionPerformanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('promises_kept', models.PositiveIntegerField(default=0)),
                ('promises_broken', models.PositiveIntegerField(default=0)),
                ('tasks_completed', models.PositiveIntegerField(default=0)),
                ('collected_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'day'), name='uniq_collection_perf_day')],
            },
        ),
        migrations.CreateModel(
            name='CustomerBalanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('overdue_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('invoice_count', models.PositiveIntegerField(default=0)),
                ('snapshot_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_snapshots', to='customers.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'snapshot_at'], name='dashboard_c_organiz_ad238a_idx'), models.Index(fields=['organization', 'customer'], name='dashboard_c_organiz_91f7f0_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationDailyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('open_invoice_count', models.PositiveIntegerField(default=0)),
                ('overdue_invoice_count', models.PositiveIntegerField(default=0)),
                ('open_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('overdue_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('collected_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('tasks_created', models.PositiveIntegerField(default=0)),
                ('tasks_completed', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'day'], name='dashboard_o_organiz_2e852a_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'day'), name='uniq_org_daily_metrics_day')],
            },
        ),
    ]
