# Generated by Django 5.2.16 on 2026-08-07 21:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0004_np211_214_workflow_engine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('high_value_payment_cancel', 'Yüksek tutarlı ödeme iptali'), ('bulk_message', 'Toplu mesaj gönderimi'), ('legal_handoff', 'Hukuki sürece aktarma'), ('credit_limit_change', 'Kredi limiti değiştirme'), ('manual_risk_change', 'Manuel risk durumu değişikliği'), ('large_payment_plan', 'Büyük ödeme planı')], max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Bekliyor'), ('APPROVED', 'Onaylandı'), ('REJECTED', 'Reddedildi'), ('CANCELLED', 'İptal')], default='PENDING', max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True)),
                ('decision_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests_decided', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DataExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datasets', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('PENDING', 'Bekliyor'), ('RUNNING', 'Çalışıyor'), ('READY', 'Hazır'), ('FAILED', 'Başarısız'), ('EXPIRED', 'Süresi doldu')], default='PENDING', max_length=16)),
                ('file_path', models.CharField(blank=True, max_length=512)),
                ('row_counts', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_export_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(max_length=32)),
                ('target_id', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Bekliyor'), ('WAITING', 'Bekleme süresi'), ('CANCELLED', 'İptal'), ('PROCESSING', 'İşleniyor'), ('COMPLETED', 'Tamamlandı')], default='PENDING', max_length=16)),
                ('waiting_until', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_report', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SSOProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(choices=[('SAML', 'SAML'), ('OIDC', 'OpenID Connect'), ('GOOGLE_WORKSPACE', 'Google Workspace'), ('MICROSOFT_ENTRA', 'Microsoft Entra ID')], max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('is_enabled', models.BooleanField(default=False)),
                ('issuer_url', models.URLField(blank=True)),
                ('client_id', models.CharField(blank=True, max_length=255)),
                ('metadata_url', models.URLField(blank=True)),
                ('entity_id', models.CharField(blank=True, max_length=255)),
                ('acs_url', models.URLField(blank=True)),
                ('domains', models.JSONField(blank=True, default=list)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'SSO provider config',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_jti', models.CharField(db_index=True, max_length=64, unique=True)),
                ('device_label', models.CharField(blank=True, max_length=128)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-last_seen_at',),
            },
        ),
        migrations.CreateModel(
            name='DataAccessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view_customer', 'Müşteri görüntüleme'), ('download_report', 'Rapor indirme'), ('export_data', 'Veri dışa aktarma'), ('access_integration', 'Entegrasyon erişimi')], max_length=32)),
                ('resource_type', models.CharField(max_length=64)),
                ('resource_id', models.CharField(blank=True, max_length=64)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_access_events', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['organization', 'action', 'created_at'], name='governance__organiz_3b990b_idx'), models.Index(fields=['organization', 'actor', 'created_at'], name='governance__organiz_0ca425_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProcessingInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(max_length=128)),
                ('data_type', models.CharField(max_length=64)),
                ('purpose', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=128)),
                ('retention_days', models.PositiveIntegerField(default=0)),
                ('roles_allowed', models.JSONField(blank=True, default=list)),
                ('transferred_systems', models.JSONField(blank=True, default=list)),
                ('deletion_method', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'ordering': ('field_key',),
                'constraints': [models.UniqueConstraint(fields=('organization', 'field_key'), name='uniq_processing_inventory_field')],
            },
        ),
        migrations.CreateModel(
            name='RetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_logs_days', models.PositiveIntegerField(default=1825)),
                ('audit_logs_days', models.PositiveIntegerField(default=3650)),
                ('import_files_days', models.PositiveIntegerField(default=90)),
                ('failed_webhook_bodies_days', models.PositiveIntegerField(default=30)),
                ('ai_requests_days', models.PositiveIntegerField(default=30)),
                ('deleted_user_data_days', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'verbose_name_plural': 'retention policies',
                'constraints': [models.UniqueConstraint(fields=('organization',), name='uniq_retention_policy_per_org')],
            },
        ),
    ]
