# Generated by Django 5.2.16 on 2026-07-31 18:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0001_epic7_payments'),
        ('customers', '0002_customer_last_contact_at_customer_risk_score_and_more'),
        ('invoices', '0002_invoice_payment_completion_date_and_more'),
        ('organizations', '0003_invitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentpromise',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_promises', to='invoices.invoice'),
        ),
        migrations.CreateModel(
            name='CollectionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('CALL', 'Call'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('FOLLOW_UP', 'Follow-up'), ('MEETING', 'Meeting'), ('OTHER', 'Other')], default='CALL', max_length=32)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=32)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=16)),
                ('priority_score', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField()),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('OVERDUE_INVOICE', 'Overdue invoice'), ('BROKEN_PROMISE', 'Broken promise'), ('FOLLOW_UP', 'Follow-up')], default='MANUAL', max_length=32)),
                ('outcome', models.CharField(blank=True, choices=[('REACHED', 'Ulaşıldı'), ('NOT_REACHED', 'Ulaşılamadı'), ('PAYMENT_MADE', 'Ödeme yapıldı'), ('PROMISE_GIVEN', 'Ödeme sözü verdi'), ('DISPUTED', 'İtiraz etti'), ('WRONG_PERSON', 'Yanlış kişi'), ('CALLBACK', 'Tekrar aranacak')], max_length=32)),
                ('outcome_notes', models.TextField(blank=True)),
                ('callback_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_collection_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_collection_tasks', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_tasks', to='customers.customer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_tasks', to='invoices.invoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('related_promise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_tasks', to='collections.paymentpromise')),
            ],
            options={
                'verbose_name': 'collection task',
                'verbose_name_plural': 'collection tasks',
                'ordering': ('due_date', '-priority_score', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CollectionActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('CALL', 'Telefon görüşmesi'), ('EMAIL', 'E-posta'), ('WHATSAPP', 'WhatsApp'), ('TASK_COMPLETED', 'Görev tamamlandı'), ('PROMISE', 'Ödeme sözü'), ('PAYMENT', 'Ödeme'), ('NOTE', 'Not'), ('OTHER', 'Diğer')], default='NOTE', max_length=32)),
                ('summary', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_activities', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_activities', to='customers.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='collections.collectiontask')),
            ],
            options={
                'verbose_name': 'collection activity',
                'verbose_name_plural': 'collection activities',
                'ordering': ('-occurred_at', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='collectiontask',
            index=models.Index(fields=['organization', 'status', 'due_date'], name='collections_organiz_7ac54b_idx'),
        ),
        migrations.AddIndex(
            model_name='collectiontask',
            index=models.Index(fields=['organization', 'assigned_to', 'status'], name='collections_organiz_0ce27f_idx'),
        ),
    ]
