# Generated by Django 5.2.17 on 2026-08-07 21:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0002_epic8_collection_tasks'),
        ('customers', '0004_np211_214_workflow_engine'),
        ('invoices', '0003_np194_invoice_source_external'),
        ('organizations', '0004_np211_214_workflow_engine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('INVOICE_ERROR', 'Fatura hatası'), ('MISSING_DELIVERY', 'Eksik teslimat'), ('SERVICE_DISPUTE', 'Hizmet uyuşmazlığı'), ('PRICE_DISPUTE', 'Fiyat itirazı'), ('TAX_ERROR', 'Vergi bilgisi hatası'), ('UNAUTHORIZED_INVOICE', 'Yetkisiz fatura'), ('DUPLICATE_INVOICE', 'Mükerrer fatura'), ('OTHER', 'Diğer')], max_length=32)),
                ('status', models.CharField(choices=[('OPEN', 'Açık'), ('IN_REVIEW', 'İnceleniyor'), ('RESOLVED', 'Çözüldü'), ('REJECTED', 'Reddedildi'), ('CANCELLED', 'İptal')], db_index=True, default='OPEN', max_length=16)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_disputes', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_disputes', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='customers.customer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes', to='invoices.invoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'dispute',
                'verbose_name_plural': 'disputes',
                'ordering': ('-opened_at', '-id'),
                'indexes': [models.Index(fields=['organization', 'status', 'opened_at'], name='collections_organiz_78e337_idx'), models.Index(fields=['organization', 'customer', 'status'], name='collections_organiz_d05062_idx')],
            },
        ),
    ]
