# Generated by Django 5.2.17 on 2026-08-07 21:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0003_np242_250_whatsapp_prefs_disputes'),
        ('customers', '0005_np242_250_whatsapp_prefs_disputes'),
        ('invoices', '0003_np194_invoice_source_external'),
        ('organizations', '0004_np211_214_workflow_engine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisputeAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('PDF', 'PDF'), ('IMAGE', 'Görsel'), ('DELIVERY_DOC', 'Teslimat belgesi'), ('EMAIL', 'E-posta'), ('CONTRACT', 'Sözleşme')], default='PDF', max_length=32)),
                ('original_filename', models.CharField(max_length=255)),
                ('stored_path', models.CharField(max_length=512)),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'dispute attachment',
                'verbose_name_plural': 'dispute attachments',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DisputeStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=32)),
                ('to_status', models.CharField(choices=[('OPEN', 'Açık'), ('UNDER_REVIEW', 'İncelemede'), ('WAITING_CUSTOMER', 'Müşteri bekleniyor'), ('WAITING_INTERNAL', 'İç birim bekleniyor'), ('RESOLVED', 'Çözüldü'), ('REJECTED', 'Reddedildi'), ('CANCELLED', 'İptal')], max_length=32)),
                ('note', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'dispute status event',
                'verbose_name_plural': 'dispute status events',
                'ordering': ('-occurred_at', '-id'),
            },
        ),
        migrations.AlterField(
            model_name='dispute',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Açık'), ('UNDER_REVIEW', 'İncelemede'), ('WAITING_CUSTOMER', 'Müşteri bekleniyor'), ('WAITING_INTERNAL', 'İç birim bekleniyor'), ('RESOLVED', 'Çözüldü'), ('REJECTED', 'Reddedildi'), ('CANCELLED', 'İptal')], db_index=True, default='OPEN', max_length=32),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['organization', 'invoice', 'status'], name='collections_organiz_b4d037_idx'),
        ),
        migrations.AddField(
            model_name='disputeattachment',
            name='dispute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='collections.dispute'),
        ),
        migrations.AddField(
            model_name='disputeattachment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='disputeattachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispute_attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disputestatusevent',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispute_status_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disputestatusevent',
            name='dispute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='collections.dispute'),
        ),
        migrations.AddField(
            model_name='disputestatusevent',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
    ]
