# Generated by Django 5.2.16 on 2026-08-07 22:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0005_rename_in_review_to_under_review'),
        ('customers', '0006_np282_294_billing_onboarding'),
        ('organizations', '0005_np300_315_enterprise_kvkk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='collectionactivity',
            index=models.Index(fields=['organization', 'occurred_at'], name='act_org_occurred_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionactivity',
            index=models.Index(fields=['organization', 'customer', 'occurred_at'], name='act_org_cust_occurred_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionactivity',
            index=models.Index(fields=['organization', 'created_at'], name='act_org_created_idx'),
        ),
    ]
