# Generated by Django 5.2.16 on 2026-08-03 21:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0004_np211_214_workflow_engine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('customer_summary', 'Customer summary'), ('call_prep', 'Call preparation'), ('note_parse', 'Note parsing'), ('message_assistant', 'Message assistant'), ('payment_plan', 'Payment plan'), ('generic', 'Generic')], db_index=True, max_length=64)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=6, default=Decimal('0.0000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('model', models.CharField(default='deterministic', max_length=64)),
                ('cache_hit', models.BooleanField(default=False)),
                ('truncated', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI usage event',
                'verbose_name_plural': 'AI usage events',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['organization', 'created_at'], name='ai_usage_ai_organiz_4a3eb3_idx'), models.Index(fields=['organization', 'user', 'created_at'], name='ai_usage_ai_organiz_dc1664_idx'), models.Index(fields=['organization', 'feature', 'created_at'], name='ai_usage_ai_organiz_5ebe03_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIUsageLimitConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='starter', max_length=32)),
                ('package_monthly_tokens', models.PositiveIntegerField(default=100000)),
                ('daily_user_tokens', models.PositiveIntegerField(default=10000)),
                ('org_budget_monthly', models.DecimalField(decimal_places=4, default=Decimal('50.0000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('max_input_chars', models.PositiveIntegerField(default=8000)),
                ('cache_ttl_seconds', models.PositiveIntegerField(default=3600)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'AI usage limit config',
                'verbose_name_plural': 'AI usage limit configs',
                'constraints': [models.UniqueConstraint(fields=('organization',), name='ai_usage_limit_one_per_org')],
            },
        ),
    ]
