# Generated by Django 5.2.16 on 2026-08-08 12:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0007_np320_336_scale_ops'),
        ('governance', '0001_np300_315_enterprise_kvkk'),
        ('invoices', '0005_np320_336_scale_ops'),
        ('organizations', '0006_np340_354_pwa_legal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PREPARING', 'Hazırlanıyor'), ('HANDED_TO_LAWYER', 'Avukata aktarıldı'), ('NOTICE', 'İhtar aşaması'), ('MEDIATION', 'Arabuluculuk'), ('LAWSUIT', 'Dava'), ('ENFORCEMENT', 'İcra'), ('COLLECTED', 'Tahsil edildi'), ('CLOSED', 'Kapatıldı')], db_index=True, default='PREPARING', max_length=32)),
                ('balance_at_open', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('criteria_snapshot', models.JSONField(blank=True, default=dict)),
                ('manager_approved', models.BooleanField(default=False)),
                ('manager_approved_at', models.DateTimeField(blank=True, null=True)),
                ('package_path', models.CharField(blank=True, max_length=512)),
                ('package_generated_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_cases', to='governance.approvalrequest')),
                ('assigned_lawyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_legal_cases', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_legal_cases', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_cases', to='customers.customer')),
                ('manager_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_legal_cases', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'legal case',
                'verbose_name_plural': 'legal cases',
                'ordering': ('-opened_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='LegalCaseActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('is_lawyer_visible', models.BooleanField(default=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_case_activities', to=settings.AUTH_USER_MODEL)),
                ('legal_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='legal.legalcase')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'legal case activity',
                'verbose_name_plural': 'legal case activities',
                'ordering': ('-occurred_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='LegalCaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('stored_path', models.CharField(max_length=512)),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('legal_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='legal.legalcase')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_case_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'legal case document',
                'verbose_name_plural': 'legal case documents',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LegalCaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_at_link', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_case_links', to='invoices.invoice')),
                ('legal_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_invoices', to='legal.legalcase')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'legal case invoice',
                'verbose_name_plural': 'legal case invoices',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LegalCaseStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=32)),
                ('to_status', models.CharField(choices=[('PREPARING', 'Hazırlanıyor'), ('HANDED_TO_LAWYER', 'Avukata aktarıldı'), ('NOTICE', 'İhtar aşaması'), ('MEDIATION', 'Arabuluculuk'), ('LAWSUIT', 'Dava'), ('ENFORCEMENT', 'İcra'), ('COLLECTED', 'Tahsil edildi'), ('CLOSED', 'Kapatıldı')], max_length=32)),
                ('note', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_status_changes', to=settings.AUTH_USER_MODEL)),
                ('legal_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='legal.legalcase')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'legal case status history',
                'verbose_name_plural': 'legal case status histories',
                'ordering': ('-occurred_at', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='legalcase',
            index=models.Index(fields=['organization', 'status'], name='legal_legal_organiz_dbddbc_idx'),
        ),
        migrations.AddIndex(
            model_name='legalcase',
            index=models.Index(fields=['organization', 'assigned_lawyer'], name='legal_legal_organiz_eb4161_idx'),
        ),
        migrations.AddIndex(
            model_name='legalcase',
            index=models.Index(fields=['organization', 'customer'], name='legal_legal_organiz_c9b93b_idx'),
        ),
        migrations.AddConstraint(
            model_name='legalcaseinvoice',
            constraint=models.UniqueConstraint(fields=('legal_case', 'invoice'), name='legal_case_invoice_uniq'),
        ),
    ]
