# Generated by Django 5.2.16 on 2026-07-31 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('channel', models.CharField(choices=[('EMAIL', 'E-posta'), ('WHATSAPP', 'WhatsApp'), ('SMS', 'SMS')], max_length=16)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'message template',
                'verbose_name_plural': 'message templates',
                'ordering': ('channel', 'name', 'id'),
                'indexes': [models.Index(fields=['organization', 'channel', 'is_default'], name='messaging_m_organiz_5babfa_idx')],
            },
        ),
    ]
