# Generated by Django 5.2.16 on 2026-08-03 21:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0002_epic8_collection_tasks'),
        ('customers', '0004_np211_214_workflow_engine'),
        ('invoices', '0003_np194_invoice_source_external'),
        ('messaging', '0001_epic13_message_templates'),
        ('organizations', '0004_np211_214_workflow_engine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tracking_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body_text', models.TextField()),
                ('body_html', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('PENDING_APPROVAL', 'Onay bekliyor'), ('APPROVED', 'Onaylandı'), ('QUEUED', 'Kuyrukta'), ('SENDING', 'Gönderiliyor'), ('SENT', 'Gönderildi'), ('DELIVERED', 'Teslim edildi'), ('OPENED', 'Açıldı'), ('CLICKED', 'Tıklandı'), ('BOUNCED', 'Bounce'), ('FAILED', 'Başarısız'), ('CANCELLED', 'İptal')], db_index=True, default='PENDING_APPROVAL', max_length=32)),
                ('provider', models.CharField(blank=True, max_length=16)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('bounced_at', models.DateTimeField(blank=True, null=True)),
                ('open_count', models.PositiveIntegerField(default=0)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('bounce_type', models.CharField(blank=True, max_length=64)),
                ('bounce_detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_emails', to='collections.collectionactivity')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_outbound_emails', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_outbound_emails', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_emails', to='customers.customer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_emails', to='invoices.invoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_emails', to='messaging.messagetemplate')),
            ],
            options={
                'verbose_name': 'outbound email',
                'verbose_name_plural': 'outbound emails',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='EmailTrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('QUEUED', 'Kuyruğa alındı'), ('SENT', 'Gönderildi'), ('DELIVERED', 'Teslim'), ('OPEN', 'Açılma'), ('CLICK', 'Tıklama'), ('BOUNCE', 'Bounce'), ('FAILED', 'Hata'), ('APPROVED', 'Onay')], max_length=16)),
                ('url', models.TextField(blank=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='messaging.outboundemail')),
            ],
            options={
                'verbose_name': 'email tracking event',
                'verbose_name_plural': 'email tracking events',
                'ordering': ('-occurred_at',),
            },
        ),
        migrations.CreateModel(
            name='EmailProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('SMTP', 'SMTP'), ('API', 'Sağlayıcı API'), ('CONSOLE', 'Konsol (geliştirme)')], default='SMTP', max_length=16)),
                ('from_email', models.EmailField(max_length=254)),
                ('from_name', models.CharField(blank=True, max_length=128)),
                ('smtp_host', models.CharField(blank=True, max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('smtp_use_ssl', models.BooleanField(default=False)),
                ('encrypted_credentials', models.TextField(blank=True)),
                ('key_hint', models.CharField(blank=True, max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'email provider config',
                'verbose_name_plural': 'email provider configs',
                'constraints': [models.UniqueConstraint(fields=('organization',), name='messaging_email_provider_one_per_org')],
            },
        ),
        migrations.AddIndex(
            model_name='outboundemail',
            index=models.Index(fields=['organization', 'status', 'created_at'], name='messaging_o_organiz_3e229c_idx'),
        ),
        migrations.AddIndex(
            model_name='outboundemail',
            index=models.Index(fields=['organization', 'customer', 'created_at'], name='messaging_o_organiz_68ecab_idx'),
        ),
        migrations.AddIndex(
            model_name='emailtrackingevent',
            index=models.Index(fields=['organization', 'event_type', 'occurred_at'], name='messaging_e_organiz_3378f0_idx'),
        ),
    ]
