# Generated by Django 5.2.17 on 2026-08-07 21:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0003_np242_250_whatsapp_prefs_disputes'),
        ('customers', '0005_np242_250_whatsapp_prefs_disputes'),
        ('invoices', '0003_np194_invoice_source_external'),
        ('messaging', '0002_np240_outbound_email'),
        ('organizations', '0004_np211_214_workflow_engine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_phone', models.CharField(db_index=True, max_length=32)),
                ('body', models.TextField()),
                ('provider_message_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('match_method', models.CharField(blank=True, max_length=32)),
                ('suggested_classification', models.CharField(blank=True, choices=[('PAID', 'Ödeme yaptı'), ('PROMISE', 'Ödeme sözü verdi'), ('INVOICE_DISPUTE', 'Fatura itirazı'), ('WRONG_PERSON', 'Yanlış kişi'), ('CASH_SHORTAGE', 'Nakit sıkıntısı'), ('CALLBACK_REQUEST', 'Tekrar iletişim talebi'), ('LEGAL_DISPUTE', 'Hukuki itiraz')], max_length=32)),
                ('classification', models.CharField(blank=True, choices=[('PAID', 'Ödeme yaptı'), ('PROMISE', 'Ödeme sözü verdi'), ('INVOICE_DISPUTE', 'Fatura itirazı'), ('WRONG_PERSON', 'Yanlış kişi'), ('CASH_SHORTAGE', 'Nakit sıkıntısı'), ('CALLBACK_REQUEST', 'Tekrar iletişim talebi'), ('LEGAL_DISPUTE', 'Hukuki itiraz')], max_length=32)),
                ('classification_confirmed', models.BooleanField(default=False)),
                ('classification_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('opt_out_detected', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classification_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_wa_classifications', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_whatsapp', to='customers.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'inbound WhatsApp',
                'verbose_name_plural': 'inbound WhatsApp messages',
                'ordering': ('-received_at',),
            },
        ),
        migrations.CreateModel(
            name='WhatsAppApprovedTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('language_code', models.CharField(default='tr', max_length=16)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('body', models.TextField()),
                ('header', models.CharField(blank=True, max_length=255)),
                ('footer', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('PENDING', 'Onay bekliyor'), ('APPROVED', 'Onaylı'), ('REJECTED', 'Reddedildi'), ('PAUSED', 'Duraklatıldı')], db_index=True, default='DRAFT', max_length=16)),
                ('external_template_id', models.CharField(blank=True, max_length=128)),
                ('variables_schema', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_approvals', to='messaging.messagetemplate')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'WhatsApp approved template',
                'verbose_name_plural': 'WhatsApp approved templates',
                'ordering': ('name', 'language_code', 'id'),
            },
        ),
        migrations.CreateModel(
            name='OutboundWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('to_phone', models.CharField(max_length=32)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('QUEUED', 'Kuyrukta'), ('SENDING', 'Gönderiliyor'), ('SENT', 'Gönderildi'), ('DELIVERED', 'Teslim edildi'), ('READ', 'Okundu'), ('FAILED', 'Başarısız'), ('CANCELLED', 'İptal'), ('SKIPPED', 'Atlandı')], db_index=True, default='DRAFT', max_length=16)),
                ('is_automatic', models.BooleanField(db_index=True, default=False)),
                ('batch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('skip_reason', models.CharField(blank=True, max_length=128)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_whatsapp', to='collections.collectionactivity')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_outbound_whatsapp', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_whatsapp', to='customers.customer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_whatsapp', to='invoices.invoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_messages', to='messaging.whatsappapprovedtemplate')),
            ],
            options={
                'verbose_name': 'outbound WhatsApp',
                'verbose_name_plural': 'outbound WhatsApp messages',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WhatsAppOptOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('opted_out_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('opted_in_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_opt_outs', to='customers.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('source_inbound', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opt_outs', to='messaging.inboundwhatsapp')),
            ],
            options={
                'verbose_name': 'WhatsApp opt-out',
                'verbose_name_plural': 'WhatsApp opt-outs',
                'ordering': ('-opted_out_at',),
            },
        ),
        migrations.CreateModel(
            name='WhatsAppProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number_id', models.CharField(blank=True, max_length=64)),
                ('waba_id', models.CharField(blank=True, max_length=64)),
                ('display_phone', models.CharField(blank=True, max_length=32)),
                ('encrypted_credentials', models.TextField(blank=True)),
                ('key_hint', models.CharField(blank=True, max_length=16)),
                ('mock_mode', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'WhatsApp provider config',
                'verbose_name_plural': 'WhatsApp provider configs',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('QUEUED', 'Kuyrukta'), ('SENDING', 'Gönderiliyor'), ('SENT', 'Gönderildi'), ('DELIVERED', 'Teslim edildi'), ('READ', 'Okundu'), ('FAILED', 'Başarısız'), ('CANCELLED', 'İptal'), ('SKIPPED', 'Atlandı')], max_length=16)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='messaging.outboundwhatsapp')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'WhatsApp status event',
                'verbose_name_plural': 'WhatsApp status events',
                'ordering': ('-occurred_at',),
            },
        ),
        migrations.AddIndex(
            model_name='inboundwhatsapp',
            index=models.Index(fields=['organization', 'from_phone', 'received_at'], name='messaging_i_organiz_cfa73d_idx'),
        ),
        migrations.AddIndex(
            model_name='inboundwhatsapp',
            index=models.Index(fields=['organization', 'customer', 'received_at'], name='messaging_i_organiz_69e781_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappapprovedtemplate',
            index=models.Index(fields=['organization', 'status'], name='messaging_w_organiz_244a42_idx'),
        ),
        migrations.AddConstraint(
            model_name='whatsappapprovedtemplate',
            constraint=models.UniqueConstraint(fields=('organization', 'name', 'language_code'), name='messaging_wa_template_uniq_org_name_lang'),
        ),
        migrations.AddIndex(
            model_name='outboundwhatsapp',
            index=models.Index(fields=['organization', 'status', 'created_at'], name='messaging_o_organiz_f0c0ab_idx'),
        ),
        migrations.AddIndex(
            model_name='outboundwhatsapp',
            index=models.Index(fields=['organization', 'customer', 'created_at'], name='messaging_o_organiz_d0fd4f_idx'),
        ),
        migrations.AddIndex(
            model_name='outboundwhatsapp',
            index=models.Index(fields=['organization', 'customer', 'is_automatic', 'sent_at'], name='messaging_o_organiz_dc3836_idx'),
        ),
        migrations.AddConstraint(
            model_name='whatsappoptout',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('organization', 'phone'), name='messaging_wa_optout_active_uniq'),
        ),
        migrations.AddConstraint(
            model_name='whatsappproviderconfig',
            constraint=models.UniqueConstraint(fields=('organization',), name='messaging_wa_provider_one_per_org'),
        ),
    ]
