# Generated by Django 5.2.16 on 2026-08-02 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collections', '0002_epic8_collection_tasks'),
        ('customers', '0003_np193_customer_source_external'),
        ('invoices', '0003_np194_invoice_source_external'),
        ('organizations', '0003_invitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('trigger_type', models.CharField(choices=[('invoice_overdue', 'Invoice overdue'), ('promise_broken', 'Payment promise broken'), ('manual', 'Manual')], db_index=True, max_length=32)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_collection_workflows', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'collection workflow',
                'verbose_name_plural': 'collection workflows',
                'ordering': ('priority', 'name'),
            },
        ),
        migrations.CreateModel(
            name='WorkflowAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create_task', 'Create collection task'), ('notify', 'Send notification / dashboard alert'), ('recalculate_risk', 'Recalculate customer risk')], max_length=32)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'workflow action',
                'verbose_name_plural': 'workflow actions',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='WorkflowExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('invoice_overdue', 'Invoice overdue'), ('promise_broken', 'Payment promise broken'), ('manual', 'Manual')], db_index=True, max_length=32)),
                ('trigger_entity_type', models.CharField(max_length=64)),
                ('trigger_entity_id', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=16)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_executions', to='customers.customer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_executions', to='invoices.invoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('promise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_executions', to='collections.paymentpromise')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='workflows.collectionworkflow')),
            ],
            options={
                'verbose_name': 'workflow execution',
                'verbose_name_plural': 'workflow executions',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('stop_on_match', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflows.collectionworkflow')),
            ],
            options={
                'verbose_name': 'workflow step',
                'verbose_name_plural': 'workflow steps',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='WorkflowExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('started', 'Started'), ('condition_match', 'Condition matched'), ('condition_miss', 'Condition not matched'), ('action_ok', 'Action succeeded'), ('action_fail', 'Action failed'), ('step_skipped', 'Step skipped'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=32)),
                ('message', models.CharField(blank=True, default='', max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_logs', to='workflows.workflowaction')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='workflows.workflowexecution')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_logs', to='workflows.workflowstep')),
            ],
            options={
                'verbose_name': 'workflow execution log',
                'verbose_name_plural': 'workflow execution logs',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='WorkflowCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('invoice.overdue_days', 'Invoice overdue days'), ('invoice.status', 'Invoice status'), ('promise.status', 'Promise status'), ('customer.risk_level', 'Customer risk level')], max_length=64)),
                ('operator', models.CharField(choices=[('eq', 'Equals'), ('ne', 'Not equals'), ('gt', 'Greater than'), ('gte', 'Greater or equal'), ('lt', 'Less than'), ('lte', 'Less or equal'), ('in', 'In'), ('not_in', 'Not in')], default='gte', max_length=16)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('logic', models.CharField(choices=[('and', 'AND'), ('or', 'OR')], default='and', help_text='How this condition combines with other conditions on the same step.', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='workflows.workflowstep')),
            ],
            options={
                'verbose_name': 'workflow condition',
                'verbose_name_plural': 'workflow conditions',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='workflowaction',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='workflows.workflowstep'),
        ),
        migrations.AddIndex(
            model_name='collectionworkflow',
            index=models.Index(fields=['organization', 'trigger_type', 'is_active'], name='wf_org_trigger_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='collectionworkflow',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uniq_wf_org_name'),
        ),
        migrations.AddIndex(
            model_name='workflowexecution',
            index=models.Index(fields=['organization', 'status', 'created_at'], name='wf_exec_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowexecution',
            index=models.Index(fields=['trigger_entity_type', 'trigger_entity_id'], name='wf_exec_entity_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflowexecution',
            constraint=models.UniqueConstraint(fields=('organization', 'idempotency_key'), name='uniq_wf_exec_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='workflowstep',
            constraint=models.UniqueConstraint(fields=('workflow', 'order'), name='uniq_wf_step_order'),
        ),
        migrations.AddIndex(
            model_name='workflowexecutionlog',
            index=models.Index(fields=['execution', 'created_at'], name='wf_log_exec_created_idx'),
        ),
    ]
