# Generated by Django 5.2.16 on 2026-08-02 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0002_epic8_collection_tasks'),
        ('customers', '0004_np211_214_workflow_engine'),
        ('invoices', '0003_np194_invoice_source_external'),
        ('organizations', '0004_np211_214_workflow_engine'),
        ('workflows', '0001_np210_workflow_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=16)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('message', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'workflow approval request',
                'verbose_name_plural': 'workflow approval requests',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WorkflowEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_handle', models.CharField(choices=[('next', 'Next'), ('true', 'True'), ('false', 'False')], default='next', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'workflow edge',
                'verbose_name_plural': 'workflow edges',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='collectionworkflow',
            name='canvas_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='workflowexecution',
            name='current_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_executions', to='workflows.workflowstep'),
        ),
        migrations.AddField(
            model_name='workflowexecution',
            name='resume_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='client_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='position_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='position_y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='step_type',
            field=models.CharField(choices=[('trigger', 'Trigger'), ('condition', 'Condition'), ('delay', 'Delay'), ('action', 'Action'), ('branch', 'Branch'), ('stop', 'Stop')], db_index=True, default='action', max_length=16),
        ),
        migrations.AlterField(
            model_name='collectionworkflow',
            name='trigger_type',
            field=models.CharField(choices=[('invoice_overdue', 'Fatura gecikti'), ('risk_level_changed', 'Risk seviyesi değişti'), ('promise_made', 'Ödeme sözü verildi'), ('promise_broken', 'Ödeme sözü bozuldu'), ('payment_received', 'Yeni ödeme geldi'), ('customer_unreachable', 'Müşteriye ulaşılamadı'), ('open_balance_exceeded', 'Açık bakiye limiti aştı'), ('manual', 'Manuel')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='workflowaction',
            name='action_type',
            field=models.CharField(choices=[('create_task', 'Görev oluştur'), ('assign_user', 'Kullanıcıya ata'), ('notify', 'Bildirim gönder'), ('prepare_email', 'E-posta hazırla'), ('send_email', 'E-posta gönder'), ('recalculate_risk', 'Risk hesapla'), ('add_tag', 'Etiket ekle'), ('change_assignee', 'Müşteri sorumlusunu değiştir'), ('trigger_webhook', 'Webhook tetikle'), ('request_approval', 'Yönetici onayı iste')], max_length=32),
        ),
        migrations.AlterField(
            model_name='workflowcondition',
            name='field',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='workflowcondition',
            name='logic',
            field=models.CharField(choices=[('and', 'AND'), ('or', 'OR')], default='and', max_length=8),
        ),
        migrations.AlterField(
            model_name='workflowcondition',
            name='operator',
            field=models.CharField(choices=[('eq', 'Equals'), ('ne', 'Not equals'), ('gt', 'Greater than'), ('gte', 'Greater or equal'), ('lt', 'Less than'), ('lte', 'Less or equal'), ('in', 'In'), ('not_in', 'Not in'), ('contains', 'Contains'), ('is_empty', 'Is empty'), ('is_not_empty', 'Is not empty'), ('equals', 'Equals'), ('not_equals', 'Not equals'), ('greater_than', 'Greater than'), ('less_than', 'Less than')], default='gte', max_length=32),
        ),
        migrations.AlterField(
            model_name='workflowexecution',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('waiting', 'Waiting'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='workflowexecution',
            name='trigger_type',
            field=models.CharField(choices=[('invoice_overdue', 'Fatura gecikti'), ('risk_level_changed', 'Risk seviyesi değişti'), ('promise_made', 'Ödeme sözü verildi'), ('promise_broken', 'Ödeme sözü bozuldu'), ('payment_received', 'Yeni ödeme geldi'), ('customer_unreachable', 'Müşteriye ulaşılamadı'), ('open_balance_exceeded', 'Açık bakiye limiti aştı'), ('manual', 'Manuel')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='workflowexecutionlog',
            name='event',
            field=models.CharField(choices=[('started', 'Started'), ('condition_match', 'Condition matched'), ('condition_miss', 'Condition not matched'), ('action_ok', 'Action succeeded'), ('action_fail', 'Action failed'), ('step_skipped', 'Step skipped'), ('delay_scheduled', 'Delay scheduled'), ('delay_resumed', 'Delay resumed'), ('approval_requested', 'Approval requested'), ('approval_decided', 'Approval decided'), ('branch_taken', 'Branch taken'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=32),
        ),
        migrations.AddIndex(
            model_name='workflowexecution',
            index=models.Index(fields=['status', 'resume_at'], name='wf_exec_waiting_resume_idx'),
        ),
        migrations.AddField(
            model_name='workflowapprovalrequest',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_approvals_decided', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflowapprovalrequest',
            name='execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='workflows.workflowexecution'),
        ),
        migrations.AddField(
            model_name='workflowapprovalrequest',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='workflowapprovalrequest',
            name='requested_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_approvals_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflowapprovalrequest',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='workflows.workflowstep'),
        ),
        migrations.AddField(
            model_name='workflowedge',
            name='from_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_edges', to='workflows.workflowstep'),
        ),
        migrations.AddField(
            model_name='workflowedge',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='workflowedge',
            name='to_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_edges', to='workflows.workflowstep'),
        ),
        migrations.AddField(
            model_name='workflowedge',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='workflows.collectionworkflow'),
        ),
        migrations.AddConstraint(
            model_name='workflowedge',
            constraint=models.UniqueConstraint(fields=('from_step', 'source_handle'), name='uniq_wf_edge_from_handle'),
        ),
    ]
