# Generated by Django 5.2.16 on 2026-08-02 21:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_np211_214_workflow_engine'),
        ('workflows', '0002_np211_214_workflow_engine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionworkflow',
            options={'ordering': ('priority', 'name', '-version'), 'verbose_name': 'collection workflow', 'verbose_name_plural': 'collection workflows'},
        ),
        migrations.RemoveConstraint(
            model_name='collectionworkflow',
            name='uniq_wf_org_name',
        ),
        migrations.AddField(
            model_name='collectionworkflow',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collectionworkflow',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_collection_workflows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collectionworkflow',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16),
        ),
        migrations.AddField(
            model_name='collectionworkflow',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='collectionworkflow',
            name='workflow_key',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=36),
        ),
        migrations.AlterField(
            model_name='collectionworkflow',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='collectionworkflow',
            index=models.Index(fields=['organization', 'trigger_type', 'status'], name='wf_org_trigger_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='collectionworkflow',
            constraint=models.UniqueConstraint(fields=('organization', 'workflow_key', 'version'), name='uniq_wf_org_key_version'),
        ),
    ]
