# Generated by Django 5.2.16 on 2026-08-02 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_invitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('url', models.URLField(max_length=2048)),
                ('description', models.TextField(blank=True, default='')),
                ('secret_encrypted', models.TextField()),
                ('secret_hint', models.CharField(blank=True, default='', max_length=16)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_webhook_endpoints', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'webhook endpoint',
                'verbose_name_plural': 'webhook endpoints',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WebhookSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('invoice.created', 'Invoice created'), ('invoice.overdue', 'Invoice overdue'), ('invoice.paid', 'Invoice paid'), ('payment.created', 'Payment created'), ('payment.cancelled', 'Payment cancelled'), ('payment_promise.created', 'Payment promise created'), ('payment_promise.broken', 'Payment promise broken'), ('customer.risk_changed', 'Customer risk changed'), ('collection_task.created', 'Collection task created'), ('forecast.updated', 'Forecast updated')], db_index=True, max_length=64)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='webhooks.webhookendpoint')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'webhook subscription',
                'verbose_name_plural': 'webhook subscriptions',
                'ordering': ('event_type',),
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('invoice.created', 'Invoice created'), ('invoice.overdue', 'Invoice overdue'), ('invoice.paid', 'Invoice paid'), ('payment.created', 'Payment created'), ('payment.cancelled', 'Payment cancelled'), ('payment_promise.created', 'Payment promise created'), ('payment_promise.broken', 'Payment promise broken'), ('customer.risk_changed', 'Customer risk changed'), ('collection_task.created', 'Collection task created'), ('forecast.updated', 'Forecast updated')], db_index=True, max_length=64)),
                ('event_id', models.CharField(db_index=True, max_length=128)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('exhausted', 'Exhausted')], db_index=True, default='pending', max_length=16)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=8)),
                ('next_attempt_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='webhooks.webhookendpoint')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='webhooks.webhooksubscription')),
            ],
            options={
                'verbose_name': 'webhook delivery',
                'verbose_name_plural': 'webhook deliveries',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WebhookAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField()),
                ('request_url', models.URLField(blank=True, default='', max_length=2048)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='webhooks.webhookdelivery')),
            ],
            options={
                'verbose_name': 'webhook attempt',
                'verbose_name_plural': 'webhook attempts',
                'ordering': ('attempt_number',),
                'constraints': [models.UniqueConstraint(fields=('delivery', 'attempt_number'), name='uniq_wh_attempt_deliv_num')],
            },
        ),
        migrations.AddIndex(
            model_name='webhookendpoint',
            index=models.Index(fields=['organization', 'is_active'], name='wh_ep_org_active_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooksubscription',
            index=models.Index(fields=['organization', 'event_type', 'is_active'], name='wh_sub_org_event_idx'),
        ),
        migrations.AddConstraint(
            model_name='webhooksubscription',
            constraint=models.UniqueConstraint(fields=('endpoint', 'event_type'), name='uniq_wh_sub_endpoint_event'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['status', 'next_attempt_at'], name='wh_deliv_status_next_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['organization', 'event_type', 'created_at'], name='wh_deliv_org_event_idx'),
        ),
        migrations.AddConstraint(
            model_name='webhookdelivery',
            constraint=models.UniqueConstraint(fields=('endpoint', 'event_type', 'event_id'), name='uniq_wh_delivery_ep_event'),
        ),
    ]
