# Generated by Django 5.2.16 on 2026-07-31 18:23

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(db_index=True)),
                ('week_index', models.PositiveSmallIntegerField(default=0)),
                ('currency', models.CharField(default='TRY', max_length=3)),
                ('nominal_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('expected_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('optimistic_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('pessimistic_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('calculation_details', models.JSONField(blank=True, default=dict)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('run_id', models.CharField(blank=True, db_index=True, default='', max_length=36)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'forecast snapshot',
                'verbose_name_plural': 'forecast snapshots',
                'ordering': ('week_start', 'id'),
                'indexes': [models.Index(fields=['organization', 'run_id', 'week_start'], name='forecasting_organiz_0a8809_idx')],
            },
        ),
    ]
