# Generated by Django 5.2.16 on 2026-07-31 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_invitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.CharField(choices=[('invoices', 'Invoices')], default='invoices', max_length=32)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('MAPPED', 'Mapped'), ('PREVIEWED', 'Previewed'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='UPLOADED', max_length=32)),
                ('original_filename', models.CharField(max_length=255)),
                ('stored_path', models.CharField(max_length=512)),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('file_hash', models.CharField(db_index=True, max_length=64)),
                ('headers', models.JSONField(blank=True, default=list)),
                ('column_mapping', models.JSONField(blank=True, default=dict, help_text='canonical_field → source header')),
                ('preview_summary', models.JSONField(blank=True, default=dict)),
                ('preview_errors', models.JSONField(blank=True, default=list)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('invalid_rows', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'import job',
                'verbose_name_plural': 'import jobs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ImportError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('field_name', models.CharField(blank=True, max_length=64)),
                ('raw_value', models.TextField(blank=True)),
                ('error_message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='imports.importjob')),
            ],
            options={
                'verbose_name': 'import error',
                'verbose_name_plural': 'import errors',
                'ordering': ('row_number', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='importjob',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'CANCELLED'), _negated=True), fields=('organization', 'file_hash'), name='uniq_import_file_hash_per_organization'),
        ),
    ]
