# Generated by Django 5.2.16 on 2026-08-02 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_keys', '0001_np200_api_keys'),
        ('organizations', '0003_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('endpoint', models.CharField(help_text='e.g. POST /api/v1/payments', max_length=128)),
                ('request_hash', models.CharField(max_length=64)),
                ('state', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed')], db_index=True, default='started', max_length=16)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_records', to='api_keys.apikey')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'idempotency record',
                'verbose_name_plural': 'idempotency records',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['organization', 'key'], name='idempotency_org_key_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'api_key', 'key'), name='uniq_idempotency_org_apikey_key')],
            },
        ),
    ]
