# Generated by Django 5.2.17 on 2026-08-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_type_href'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardalert',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('TASK_DUE', 'Görev vadesi'), ('TASK_OVERDUE', 'Gecikmiş görev'), ('PROMISE_DUE', 'Ödeme sözü vadesi'), ('PROMISE_BROKEN', 'Bozulan ödeme sözü'), ('HIGH_RISK_CUSTOMER', 'Yüksek riskli müşteri'), ('IMPORT_COMPLETED', 'İçe aktarma tamamlandı'), ('IMPORT_FAILED', 'İçe aktarma başarısız'), ('CASH_GAP', 'Nakit açığı')], db_index=True, max_length=32),
        ),
    ]
