# Generated by Django 5.2.16 on 2026-08-08 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_np271_281_cash_billing'),
        ('organizations', '0006_np340_354_pwa_legal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardalert',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('TASK_DUE', 'Görev vadesi'), ('TASK_OVERDUE', 'Gecikmiş görev'), ('TASK_ASSIGNED', 'Atanan görev'), ('PROMISE_DUE', 'Ödeme sözü vadesi'), ('PROMISE_BROKEN', 'Bozulan ödeme sözü'), ('HIGH_RISK_CUSTOMER', 'Yüksek riskli müşteri'), ('CRITICAL_CUSTOMER', 'Kritik müşteri'), ('IMPORT_COMPLETED', 'İçe aktarma tamamlandı'), ('IMPORT_FAILED', 'İçe aktarma başarısız'), ('CASH_GAP', 'Nakit açığı')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=2048)),
                ('p256dh', models.CharField(max_length=255)),
                ('auth', models.CharField(max_length=255)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'push subscription',
                'verbose_name_plural': 'push subscriptions',
                'ordering': ('-updated_at',),
                'constraints': [models.UniqueConstraint(fields=('organization', 'endpoint'), name='notifications_push_endpoint_uniq')],
            },
        ),
    ]
