# Generated by Django 5.2.16 on 2026-08-08 12:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0006_np340_354_pwa_legal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('enabled', models.BooleanField(default=False)),
                ('environments', models.JSONField(blank=True, default=list)),
                ('plan_codes', models.JSONField(blank=True, default=list)),
                ('organization_ids', models.JSONField(blank=True, default=list)),
                ('rollout_percentage', models.PositiveSmallIntegerField(default=100, help_text='0–100; deterministic hash of org/user id.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'feature flag',
                'verbose_name_plural': 'feature flags',
                'ordering': ('key',),
            },
        ),
        migrations.CreateModel(
            name='MaintenanceWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('GLOBAL', 'Tüm sistem'), ('ORGANIZATION', 'Organizasyon'), ('MODULE', 'Modül')], max_length=32)),
                ('mode', models.CharField(choices=[('FULL', 'Tam bakım (erişim kapalı)'), ('READ_ONLY', 'Salt okunur')], default='FULL', max_length=16)),
                ('module', models.CharField(blank=True, help_text='e.g. collections, legal, billing, payments', max_length=64)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_maintenance_windows', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_windows', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'maintenance window',
                'verbose_name_plural': 'maintenance windows',
                'ordering': ('-starts_at',),
            },
        ),
        migrations.CreateModel(
            name='PlatformAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('entity_type', models.CharField(max_length=64)),
                ('entity_id', models.CharField(blank=True, max_length=64)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_audit_logs', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'platform audit log',
                'verbose_name_plural': 'platform audit logs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Açık'), ('IN_PROGRESS', 'İşlemde'), ('WAITING_CUSTOMER', 'Müşteri bekleniyor'), ('RESOLVED', 'Çözüldü'), ('CLOSED', 'Kapalı')], db_index=True, default='OPEN', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_tickets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_support_tickets', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'support ticket',
                'verbose_name_plural': 'support tickets',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ImpersonationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, max_length=64)),
                ('notify_target', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impersonation_sessions', to='organizations.organization')),
                ('staff_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impersonation_sessions_as_staff', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impersonation_sessions_as_target', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'impersonation session',
                'verbose_name_plural': 'impersonation sessions',
                'ordering': ('-started_at',),
                'indexes': [models.Index(fields=['is_active', 'expires_at'], name='platform_im_is_acti_9a7f92_idx'), models.Index(fields=['target_user', 'is_active'], name='platform_im_target__c6015b_idx')],
            },
        ),
    ]
