# Generated by Django 5.2.17 on 2026-08-07 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0005_np242_250_whatsapp_prefs_disputes'),
        ('organizations', '0004_np211_214_workflow_engine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('rules', models.JSONField(blank=True, default=dict)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_segments', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'customer segment',
                'verbose_name_plural': 'customer segments',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CollectionStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('steps', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to='segments.customersegment')),
            ],
            options={
                'verbose_name': 'collection strategy',
                'verbose_name_plural': 'collection strategies',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MessageABTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('RUNNING', 'Çalışıyor'), ('PAUSED', 'Duraklatıldı'), ('COMPLETED', 'Tamamlandı')], default='DRAFT', max_length=16)),
                ('variant_a', models.JSONField(blank=True, default=dict)),
                ('variant_b', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ab_tests', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ab_tests', to='segments.customersegment')),
            ],
            options={
                'verbose_name': 'message A/B test',
                'verbose_name_plural': 'message A/B tests',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MessageABTestAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(max_length=1)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('replied', models.BooleanField(default=False)),
                ('promise_within_7d', models.BooleanField(default=False)),
                ('paid_within_7d', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ab_test_assignments', to='customers.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='segments.messageabtest')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='customersegment',
            constraint=models.UniqueConstraint(fields=('organization', 'slug'), name='segments_uniq_org_slug'),
        ),
        migrations.AddConstraint(
            model_name='messageabtestassignment',
            constraint=models.UniqueConstraint(fields=('test', 'customer'), name='segments_ab_assignment_uniq'),
        ),
    ]
